//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBMOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();

            this.ProductTitle = "";
            this.NativeTitle = "";
            this.ImageSrc = "";
            this.Category = "";
            this.SubCategory = "";
            this.Country = "";
            this.PortionWeight = "";
            this.CaloriesPer100g = " ";
            this.PortionPrice = "00.00";
            this.MainComponents = "";
            this.CookingRecipe = "";
           
        }
    
        public int Id { get; set; }
        public string ProductTitle { get; set; }
        public string NativeTitle { get; set; }
        public string ImageSrc { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string Country { get; set; }
        public string PortionPrice { get; set; }
        public string CaloriesPer100g { get; set; }
        public string PortionWeight { get; set; }
        public string MainComponents { get; set; }
        public string CookingRecipe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
